version: 2

project_name: g10k

builds:
  - id: g10k
    main: .
    binary: g10k
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.buildversion={{.Version}} -X main.buildtime={{.Date}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: g10k
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - none*

nfpms:
  - homepage: https://github.com/voxpupuli/g10k
    maintainer: Vox Pupuli <voxpupuli@groups.io>
    description: |-
      g10k is a r10k fork written in Go
    license: Apache-2.0
    formats:
      - deb
      - rpm
    provides:
      - g10k
    bindir: /usr/bin

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-dev"

release:
  # mark GitHub releases as pre-release automatically for tags like v1.0.0-rc1
  prerelease: auto

changelog:
  filters:
    exclude:
      - "^Merge pull request"
      - "^Merge branch"
