version: 2

project_name: g10k

builds:
  - id: g10k
    main: .
    binary: g10k
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.buildversion={{.Version}} -X main.buildtime={{.Date}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: g10k
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - none*

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-dev"
