// Code generated by goyacc -o puppetfile_parser.go -p pfyy puppetfile_parser.y. DO NOT EDIT.

//line puppetfile_parser.y:2
package main

import __yyfmt__ "fmt"

//line puppetfile_parser.y:2

//line puppetfile_parser.y:5
type pfyySymType struct {
	yys   int
	str   string
	attr  pfAttribute
	attrs []pfAttribute
}

const MOD = 57346
const MODULEDIR = 57347
const FORGEBASEURL = 57348
const FORGECACHETTL = 57349
const COMMA = 57350
const ARROW = 57351
const NEWLINE = 57352
const STRING = 57353
const WORD = 57354
const SYMBOL = 57355

var pfyyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"MOD",
	"MODULEDIR",
	"FORGEBASEURL",
	"FORGECACHETTL",
	"COMMA",
	"ARROW",
	"NEWLINE",
	"STRING",
	"WORD",
	"SYMBOL",
}

var pfyyStatenames = [...]string{}

const pfyyEofCode = 1
const pfyyErrCode = 2
const pfyyInitialStackSize = 16

//line puppetfile_parser.y:108

//line yacctab:1
var pfyyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const pfyyPrivate = 57344

const pfyyLast = 30

var pfyyAct = [...]int8{
	8, 14, 22, 9, 10, 11, 12, 13, 24, 25,
	23, 7, 4, 5, 6, 20, 17, 3, 16, 15,
	27, 26, 19, 2, 1, 21, 18, 0, 29, 28,
}

var pfyyPact = [...]int16{
	-1000, 7, -1000, -1000, -8, -8, -8, -10, 9, -1000,
	-1000, -1000, 8, 6, 14, -1000, -1000, -1000, 5, -3,
	-1000, 13, -1000, 11, -1000, -1000, -3, -8, -1000, -1000,
}

var pfyyPgo = [...]int8{
	0, 0, 2, 26, 25, 24, 23,
}

var pfyyR1 = [...]int8{
	0, 5, 5, 6, 6, 6, 6, 6, 3, 3,
	4, 4, 2, 2, 2, 2, 1, 1, 1,
}

var pfyyR2 = [...]int8{
	0, 0, 2, 1, 3, 3, 3, 4, 0, 2,
	1, 3, 3, 1, 1, 1, 1, 1, 1,
}

var pfyyChk = [...]int16{
	-1000, -5, -6, 10, 5, 6, 7, 4, -1, 11,
	12, 13, -1, -1, 11, 10, 10, 10, -3, 8,
	10, -4, -2, 13, 11, 12, 8, 9, -2, -1,
}

var pfyyDef = [...]int8{
	1, -2, 2, 3, 0, 0, 0, 0, 0, 16,
	17, 18, 0, 0, 8, 4, 5, 6, 0, 0,
	7, 9, 10, 13, 14, 15, 0, 0, 11, 12,
}

var pfyyTok1 = [...]int8{
	1,
}

var pfyyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13,
}

var pfyyTok3 = [...]int8{
	0,
}

var pfyyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	pfyyDebug        = 0
	pfyyErrorVerbose = false
)

type pfyyLexer interface {
	Lex(lval *pfyySymType) int
	Error(s string)
}

type pfyyParser interface {
	Parse(pfyyLexer) int
	Lookahead() int
}

type pfyyParserImpl struct {
	lval  pfyySymType
	stack [pfyyInitialStackSize]pfyySymType
	char  int
}

func (p *pfyyParserImpl) Lookahead() int {
	return p.char
}

func pfyyNewParser() pfyyParser {
	return &pfyyParserImpl{}
}

const pfyyFlag = -1000

func pfyyTokname(c int) string {
	if c >= 1 && c-1 < len(pfyyToknames) {
		if pfyyToknames[c-1] != "" {
			return pfyyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func pfyyStatname(s int) string {
	if s >= 0 && s < len(pfyyStatenames) {
		if pfyyStatenames[s] != "" {
			return pfyyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func pfyyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !pfyyErrorVerbose {
		return "syntax error"
	}

	for _, e := range pfyyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + pfyyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(pfyyPact[state])
	for tok := TOKSTART; tok-1 < len(pfyyToknames); tok++ {
		if n := base + tok; n >= 0 && n < pfyyLast && int(pfyyChk[int(pfyyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if pfyyDef[state] == -2 {
		i := 0
		for pfyyExca[i] != -1 || int(pfyyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; pfyyExca[i] >= 0; i += 2 {
			tok := int(pfyyExca[i])
			if tok < TOKSTART || pfyyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if pfyyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += pfyyTokname(tok)
	}
	return res
}

func pfyylex1(lex pfyyLexer, lval *pfyySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(pfyyTok1[0])
		goto out
	}
	if char < len(pfyyTok1) {
		token = int(pfyyTok1[char])
		goto out
	}
	if char >= pfyyPrivate {
		if char < pfyyPrivate+len(pfyyTok2) {
			token = int(pfyyTok2[char-pfyyPrivate])
			goto out
		}
	}
	for i := 0; i < len(pfyyTok3); i += 2 {
		token = int(pfyyTok3[i+0])
		if token == char {
			token = int(pfyyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(pfyyTok2[1]) /* unknown char */
	}
	if pfyyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", pfyyTokname(token), uint(char))
	}
	return char, token
}

func pfyyParse(pfyylex pfyyLexer) int {
	return pfyyNewParser().Parse(pfyylex)
}

func (pfyyrcvr *pfyyParserImpl) Parse(pfyylex pfyyLexer) int {
	var pfyyn int
	var pfyyVAL pfyySymType
	var pfyyDollar []pfyySymType
	_ = pfyyDollar // silence set and not used
	pfyyS := pfyyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	pfyystate := 0
	pfyyrcvr.char = -1
	pfyytoken := -1 // pfyyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		pfyystate = -1
		pfyyrcvr.char = -1
		pfyytoken = -1
	}()
	pfyyp := -1
	goto pfyystack

ret0:
	return 0

ret1:
	return 1

pfyystack:
	/* put a state and value onto the stack */
	if pfyyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", pfyyTokname(pfyytoken), pfyyStatname(pfyystate))
	}

	pfyyp++
	if pfyyp >= len(pfyyS) {
		nyys := make([]pfyySymType, len(pfyyS)*2)
		copy(nyys, pfyyS)
		pfyyS = nyys
	}
	pfyyS[pfyyp] = pfyyVAL
	pfyyS[pfyyp].yys = pfyystate

pfyynewstate:
	pfyyn = int(pfyyPact[pfyystate])
	if pfyyn <= pfyyFlag {
		goto pfyydefault /* simple state */
	}
	if pfyyrcvr.char < 0 {
		pfyyrcvr.char, pfyytoken = pfyylex1(pfyylex, &pfyyrcvr.lval)
	}
	pfyyn += pfyytoken
	if pfyyn < 0 || pfyyn >= pfyyLast {
		goto pfyydefault
	}
	pfyyn = int(pfyyAct[pfyyn])
	if int(pfyyChk[pfyyn]) == pfyytoken { /* valid shift */
		pfyyrcvr.char = -1
		pfyytoken = -1
		pfyyVAL = pfyyrcvr.lval
		pfyystate = pfyyn
		if Errflag > 0 {
			Errflag--
		}
		goto pfyystack
	}

pfyydefault:
	/* default state action */
	pfyyn = int(pfyyDef[pfyystate])
	if pfyyn == -2 {
		if pfyyrcvr.char < 0 {
			pfyyrcvr.char, pfyytoken = pfyylex1(pfyylex, &pfyyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if pfyyExca[xi+0] == -1 && int(pfyyExca[xi+1]) == pfyystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			pfyyn = int(pfyyExca[xi+0])
			if pfyyn < 0 || pfyyn == pfyytoken {
				break
			}
		}
		pfyyn = int(pfyyExca[xi+1])
		if pfyyn < 0 {
			goto ret0
		}
	}
	if pfyyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			pfyylex.Error(pfyyErrorMessage(pfyystate, pfyytoken))
			Nerrs++
			if pfyyDebug >= 1 {
				__yyfmt__.Printf("%s", pfyyStatname(pfyystate))
				__yyfmt__.Printf(" saw %s\n", pfyyTokname(pfyytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for pfyyp >= 0 {
				pfyyn = int(pfyyPact[pfyyS[pfyyp].yys]) + pfyyErrCode
				if pfyyn >= 0 && pfyyn < pfyyLast {
					pfyystate = int(pfyyAct[pfyyn]) /* simulate a shift of "error" */
					if int(pfyyChk[pfyystate]) == pfyyErrCode {
						goto pfyystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if pfyyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", pfyyS[pfyyp].yys)
				}
				pfyyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if pfyyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", pfyyTokname(pfyytoken))
			}
			if pfyytoken == pfyyEofCode {
				goto ret1
			}
			pfyyrcvr.char = -1
			pfyytoken = -1
			goto pfyynewstate /* try again in the same state */
		}
	}

	/* reduction by production pfyyn */
	if pfyyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", pfyyn, pfyyStatname(pfyystate))
	}

	pfyynt := pfyyn
	pfyypt := pfyyp
	_ = pfyypt // guard against "declared and not used"

	pfyyp -= int(pfyyR2[pfyyn])
	// pfyyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if pfyyp+1 >= len(pfyyS) {
		nyys := make([]pfyySymType, len(pfyyS)*2)
		copy(nyys, pfyyS)
		pfyyS = nyys
	}
	pfyyVAL = pfyyS[pfyyp+1]

	/* consult goto table to find next state */
	pfyyn = int(pfyyR1[pfyyn])
	pfyyg := int(pfyyPgo[pfyyn])
	pfyyj := pfyyg + pfyyS[pfyyp].yys + 1

	if pfyyj >= pfyyLast {
		pfyystate = int(pfyyAct[pfyyg])
	} else {
		pfyystate = int(pfyyAct[pfyyj])
		if int(pfyyChk[pfyystate]) != -pfyyn {
			pfyystate = int(pfyyAct[pfyyg])
		}
	}
	// dummy call; replaced with literal code
	switch pfyynt {

	case 4:
		pfyyDollar = pfyyS[pfyypt-3 : pfyypt+1]
//line puppetfile_parser.y:31
		{
			lex := pfyylex.(*pfLexer)
			lex.state.handleModuledir(pfyyDollar[2].str)
		}
	case 5:
		pfyyDollar = pfyyS[pfyypt-3 : pfyypt+1]
//line puppetfile_parser.y:36
		{
			lex := pfyylex.(*pfLexer)
			lex.state.handleForgeBaseURL(pfyyDollar[2].str)
		}
	case 6:
		pfyyDollar = pfyyS[pfyypt-3 : pfyypt+1]
//line puppetfile_parser.y:41
		{
			lex := pfyylex.(*pfLexer)
			lex.state.handleForgeCacheTTL(pfyyDollar[2].str, lex.currentLine)
		}
	case 7:
		pfyyDollar = pfyyS[pfyypt-4 : pfyypt+1]
//line puppetfile_parser.y:46
		{
			lex := pfyylex.(*pfLexer)
			lex.state.handleMod(pfyyDollar[2].str, pfyyDollar[3].attrs, lex.currentLine)
		}
	case 8:
		pfyyDollar = pfyyS[pfyypt-0 : pfyypt+1]
//line puppetfile_parser.y:54
		{
			pfyyVAL.attrs = nil
		}
	case 9:
		pfyyDollar = pfyyS[pfyypt-2 : pfyypt+1]
//line puppetfile_parser.y:58
		{
			pfyyVAL.attrs = pfyyDollar[2].attrs
		}
	case 10:
		pfyyDollar = pfyyS[pfyypt-1 : pfyypt+1]
//line puppetfile_parser.y:65
		{
			pfyyVAL.attrs = []pfAttribute{pfyyDollar[1].attr}
		}
	case 11:
		pfyyDollar = pfyyS[pfyypt-3 : pfyypt+1]
//line puppetfile_parser.y:69
		{
			pfyyVAL.attrs = append(pfyyDollar[1].attrs, pfyyDollar[3].attr)
		}
	case 12:
		pfyyDollar = pfyyS[pfyypt-3 : pfyypt+1]
//line puppetfile_parser.y:76
		{
			pfyyVAL.attr = pfAttribute{Name: pfyyDollar[1].str, Value: pfyyDollar[3].str, HasArrow: true}
		}
	case 13:
		pfyyDollar = pfyyS[pfyypt-1 : pfyypt+1]
//line puppetfile_parser.y:80
		{
			pfyyVAL.attr = pfAttribute{Name: pfyyDollar[1].str, Value: "", HasArrow: false}
		}
	case 14:
		pfyyDollar = pfyyS[pfyypt-1 : pfyypt+1]
//line puppetfile_parser.y:84
		{
			pfyyVAL.attr = pfAttribute{Value: pfyyDollar[1].str, IsBareValue: true}
		}
	case 15:
		pfyyDollar = pfyyS[pfyypt-1 : pfyypt+1]
//line puppetfile_parser.y:88
		{
			pfyyVAL.attr = pfAttribute{Value: pfyyDollar[1].str, IsBareValue: true}
		}
	case 16:
		pfyyDollar = pfyyS[pfyypt-1 : pfyypt+1]
//line puppetfile_parser.y:95
		{
			pfyyVAL.str = pfyyDollar[1].str
		}
	case 17:
		pfyyDollar = pfyyS[pfyypt-1 : pfyypt+1]
//line puppetfile_parser.y:99
		{
			pfyyVAL.str = pfyyDollar[1].str
		}
	case 18:
		pfyyDollar = pfyyS[pfyypt-1 : pfyypt+1]
//line puppetfile_parser.y:103
		{
			pfyyVAL.str = ":" + pfyyDollar[1].str
		}
	}
	goto pfyystack /* stack new state and value */
}
