# This is a basic workflow to help you get started with Actions

name: CI

# Triggers the workflow on push or pull request events
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    name: Test on go version ${{ matrix.go_version }} and ${{ matrix.os }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ['1.17']
        os: [ubuntu-latest, macOS-latest]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: setup go environment ${{ matrix.go_version }}
        uses: actions/setup-go@v2.1.5
        with:
          go-version: ${{ matrix.go_version }}
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: make
